{ self, inputs, ... }: {
  flake.nixosModules.hevel = { config, lib, pkgs, ... }: 
  let
    cfg = config.device.features.environments.hevel;
    user = config.internal.username;
    system = pkgs.stdenv.hostPlatform.system;

    termBin = "${pkgs.${cfg.terminal}}/bin/${cfg.terminal}";

    hevelPkg = (inputs.neu-nix.packages.${system}.hevel.override {
      conf = ''
        /* Hevel config.h - Generated by Nix */
        #include <X11/Xlib.h>
        #include <X11/Xutil.h>
        #include <xkbcommon/xkbcommon.h>

        /* 1. Appearance & Borders */
        static const unsigned int inner_border_width = ${toString cfg.borderWidth};
        static const unsigned int outer_border_width = 1; 

        static const uint32_t inner_border_color_active = ${cfg.focusColor};
        static const uint32_t inner_border_color_inactive = ${cfg.unfocusColor};
        static const uint32_t outer_border_color_active = 0xff000000;
        static const uint32_t outer_border_color_inactive = 0xff000000;

        /* 2. Terminal Identification */
        static const char *const terminal_app_ids[] = { "${cfg.terminal}", "foot", NULL };
        static const char *const select_term_app_id = "${cfg.terminal}";
        static const bool enable_terminal_spawning = true;

        /* 3. Logic & Keybindings */
        #define MOD ${cfg.modifier}

        #ifndef CONFIG_H_ONLY_CONSTANTS
        static const char *term[] = { 
            "${pkgs.coreutils}/bin/env", 
            "WAYLAND_DISPLAY=wayland-0", 
            "XDG_RUNTIME_DIR=/run/user/${toString config.users.users.${user}.uid}",
            "${termBin}", 
            NULL 
        };

        static const struct key keys[] = {
            { MOD,              XKB_KEY_Return, spawn,          {.v = term} },
            { MOD|ShiftMask,    XKB_KEY_Q,      quit,           {0} },
            ${cfg.extraKeys}
        };

        static const struct chord chords[] = {
            { Button1|Button2,  spawn,          {.v = term} },
            ${cfg.extraChords}
        };
        #endif
      '';
    }).overrideAttrs (oldAttrs: {
      buildInputs = (oldAttrs.buildInputs or []) ++ [ pkgs.libx11 ];
      postPatch = (oldAttrs.postPatch or "") + ''
        sed -i '1i#define CONFIG_H_ONLY_CONSTANTS' src/zoom.c src/scroll.c src/select.c src/window.c || true
      '';
    });
  in {
    imports = [ self.nixosModules.swc-launch ];

    options.device.features.environments.hevel = {
      enable = lib.mkEnableOption "Hevel Window Manager";
      terminal = lib.mkOption { type = lib.types.str; default = "foot"; };
      modifier = lib.mkOption { type = lib.types.str; default = "Mod4Mask"; };
      focusColor = lib.mkOption { type = lib.types.str; default = "0xff555555"; };
      unfocusColor = lib.mkOption { type = lib.types.str; default = "0xff222222"; };
      borderWidth = lib.mkOption { type = lib.types.int; default = 2; };
      extraKeys = lib.mkOption { type = lib.types.lines; default = ""; };
      extraChords = lib.mkOption { type = lib.types.lines; default = ""; };
    };

    config = lib.mkIf cfg.enable {
      environment.systemPackages = [ hevelPkg pkgs.${cfg.terminal} ];
      device.features.services.swc-launch.enable = true;
      #device.features.services.swww.enable = true;

      #environment.variables = {
      #  # Removed GBM_BACKEND to let the NVIDIA module set it correctly
      #  GDK_BACKEND = "wayland";
      #  WLR_NO_HARDWARE_CURSORS = "1";
      #  XDG_CURRENT_DESKTOP = "swc";
      #  XDG_SESSION_TYPE = "wayland";
      #};

      hardware.graphics = {
        enable = true;
        enable32Bit = true;
      };
    };
  };
}
